currentDir = io.popen("cd"):read('*l')

bomtrc = io.open("shell.bat", "w")
bomtrc:write("@echo off\n")
bomtrc:write("cd " .. currentDir .. "\n")
bomtrc:write("lua omtrc.lua -i -s -a -b %1\n")
bomtrc:close()

menureg = io.open("install.reg", "w")
menureg:write('Windows Registry Editor Version 5.00\n\n')
menureg:write('[HKEY_CLASSES_ROOT\\.osu]\n\n')
menureg:write('[HKEY_CLASSES_ROOT\\.osu\\Shell]\n\n')
menureg:write('[HKEY_CLASSES_ROOT\\.osu\\Shell\\Open]\n')
menureg:write('@=""\n\n')
menureg:write('[HKEY_CLASSES_ROOT\\.osu\\Shell\\Open\\Command]\n')
menureg:write('@="notepad %1"\n\n')
menureg:write('[HKEY_CLASSES_ROOT\\.osu\\Shell\\omtrc]\n')
menureg:write('@=""\n\n')
menureg:write('[HKEY_CLASSES_ROOT\\.osu\\Shell\\omtrc\\Command]\n')
menureg:write('@="' .. string.format("%q", currentDir):sub(2, -2) .. '\\\\shell.bat \\\"%1\\\""\n')
menureg:close()